#include<conio.h>
#include<iostream.h>
void main()
{
clrscr();
cout<<"nnnnnnnn           ii            ssssss      aaaaaaaaaaaa\n";
cout<<"nn    nn           ii            s           a          a\n";
cout<<"nn    nn           ii            ssssss      aaaaaaaaaaaa\n";
cout<<"nn    nn           ii                 s      a          a\n";
cout<<"nn    nn           ii            ssssss      a          a\n";
getch();
}